name = "rtyi"
# main = "./worker/index.ts"
compatibility_date = "2025-06-01"

routes = [
  { pattern = "rtyi.land", custom_domain = true }
]

[assets]
directory = "./docs/.vitepress/dist/"
not_found_handling = "404-page"
# binding = "ASSETS"
# run_worker_first = true

[vars]
AUTH_USERNAME = "rtyi"
AUTH_PASSWORD = "team"
