name = "rtyi"
# main = "./worker/index.ts"
compatibility_date = "2025-05-05"

[assets]
# run_worker_first = true
directory = "./docs/.vitepress/dist/"
not_found_handling = "404-page"
binding = "ASSETS"

[vars]
AUTH_USERNAME = "rtyi"
AUTH_PASSWORD = "doc"
