name = "rtyi"
main = "./worker/index.ts"
compatibility_date = "2025-05-05"

[assets]
directory = "./docs/.vitepress/dist/"
binding = "ASSETS"

[env.production.vars]
AUTH_USERNAME = "rtyi"
AUTH_PASSWORD = "doc"
