name = "rtyi"
# main = "./worker/index.ts"
compatibility_date = "2025-05-05"
routes = [
  { pattern = "rtyi.land", custom_domain = true }
]

[assets]
directory = "./docs/.vitepress/dist/"
not_found_handling = "404-page"
# run_worker_first = true
# binding = "ASSETS"

[vars]
AUTH_USERNAME = "rtyi"
AUTH_PASSWORD = "doc"
